version: '3.0'

services:
    web:
      container_name: frrc-web
      build: ./web
      image: frrc/web
      environment:
        - REACT_APP_SERVER_URL=localhost:9009
      volumes:
        - ./web/src:/app/src
        - ./web/public:/app/public
        - ./web/package.json:/app/package.json
      ports:
        - 3000:3000
      links:
        - server
      networks:
        - frrc

    server:
      container_name: frrc-server
      build: ./server
      image: frrc/server
      environment:
        - NODE_ENV=development
      volumes:
        - ./server/src:/app/src
        - ./server/public:/app/public
        - ./server/data:/app/data
        - ./server/storage:/app/storage
        - ./server/package.json:/app/package.json
      ports:
        - 9009:9009
      networks:
        - frrc

networks:
  frrc:
